# Generated by Django 5.2.1 on 2025-05-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
