# Generated by Django 5.2.1 on 2025-05-19 07:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_processor', '0003_aoi_uploaded_at_alter_aoi_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelImagery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cloud_coverage', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('queried_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagery', to='geo_processor.aoi')),
            ],
        ),
    ]
