# Generated by Django 5.2.1 on 2025-05-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_processor', '0005_sentinelimagery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_cloud', models.IntegerField(default=30)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_processor.aoi')),
            ],
        ),
    ]
