# Generated by Django 5.2.1 on 2025-06-05 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_processor', '0006_sentinelquerylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image_type', models.CharField(choices=[('true_color', 'True Color'), ('false_color', 'False Color'), ('ndvi', 'NDVI')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=225, null=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='geo_processor.aoi')),
            ],
        ),
    ]
