# Generated by Django 5.2.1 on 2025-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_processor', '0004_sentinelimagery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentinelimagery',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='sentinelimagery',
            unique_together={('aoi', 'timestamp')},
        ),
    ]
